apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: frontend
          image: amdp-registry.skala-ai.com/skala26a-cloud/team3-frontend:ffb2b7207c1267ea4a4db6cd746a3425b3a89f8d
          ports:
            - containerPort: 3001
